### ISSUE TITLE
S0nar-scanner throwing the error: org.sonar.batch.scan.ProjectLock

### ISSUE THREAD

**Issue by aitvijay** [AmadeusITGroup/sonar-stash#47]
Caused by: The folder 'src' does not exist for 'org.sonarqube:caudit-source-scanner' ,

Defect: I have Sonarcube server running in my machine. when i run sonar scanner from local to my local code it works well. but when i wanna execute the sonar-scanner on the code which is in Stash server it throws me this error. 

I have all properties set in that project sonar-project.properties.

**Comment by acopet** [comment]
Hello @aitvijay,

First of all, sorry for the delay to answer to this question. Did you manage to find a solution to your problem?

I am not sure this issue is linked to the SonarQube Bitbucket plugin. Could you please confirm you have the same behavior when you start the analysis without the plugin activation?
This issue can be linked to a wrong configuration of your sonar-project.properties. Could you please share it? 

Cheers,
Antoine

**Comment by t-8ch** [comment]
Closing, as there has been no new information for a while. If new information is provided, we  can  reopen it.
