### ISSUE TITLE
When sonar rule is opened from Bitbucket comment, can not go back go Bitbucket

### ISSUE THREAD

**Issue by kzaikin** [AmadeusITGroup/sonar-stash#53]
We have Sonar 6.0
1. Open a pull request with sonar-stash comments
2. Click sonar rule link: sonar rule page is opened
3. Click browser's Back

Browser navigates to Sonar's rules list. More Back clicks do nothing.
Expected outcome: Back goes back to Bitbucket

Rule click might open page in a new window, that would've been OK

**Comment by t-8ch** [comment]
@kzaikin Thank you for your report. Could check if this also happens with
* Links you post yourself in stash comments
* Links to sonar rules you post yourself in stash comments.

Looking at [our code](https://github.com/AmadeusITGroup/sonar-stash/blob/6e9a7b0eb1d055c1971ae86f2bdeb343b3caccda/src/main/java/org/sonar/plugins/stash/issue/MarkdownPrinter.java#L20), it just builds plain markdown and sends it to stash. So there should be links.

So I think the problem lies not with this plugin, maybe
* Bitbucket Server/Stash do not create "normal" links from markdown
* SonarQube does fancy stuff using Javascript and the browser history API.

**Comment by kzaikin** [comment]
I have posted links in sonar comments:
1. arbitrary link: opens in same window. I can go back
2. link to sonarqube rule: opens in same window, I cant't go back bitbucket, I rather go to sonar rules list as described

The problem is definitely about SonarQube doing the stuff with browser's history
Do you observe the same behavior?

I may do a pull-request with a target _blank solution from SO:
http://stackoverflow.com/questions/4425198/markdown-target-blank

**Comment by t-8ch** [comment]
@kzaikin On our 4.5 instance the back button from the rules list works fine.
Before we work around this issue here I would like to try to fix it in SonarQube proper. Could you open an issue there and post a link for it here?

**Comment by kzaikin** [comment]
I did open a topic in sonarqube group
https://groups.google.com/forum/#!topic/sonarqube/HX3y8d0zBXQ

I'm not quite sure it was a proper grop however

**Comment by t-8ch** [comment]
@kzaikin It seems no one can reproduce this issue. Do you still experience it?
I would like to close this issue, as there is nothing except workarounds we can  do from here.

While this happens you can also use middle mouse (scroll wheel) click to open those links in a new tab.

**Comment by milindbangar79** [comment]
Hi,

Would like add, that this behavior I have observed with SQ 5.5 as well.

Regards
Milind

**Comment by t-8ch** [comment]
I will close this, as it is not an issue in this plugin.
It is either a problem in your browserconfiguration, some javascript in sonarqube or some javascript in bitbucket.
We also  can't work around it with `target="_blank"`, as we are rendering only markdown and not HTML directly.
